### ISSUE TITLE
Remove JUnit from deployed version

### ISSUE THREAD

**Issue by LucianP91** [Sciss/ws4j#21]
Please get rid of the JUnit in your packaged version. Keep it only for your testing. Don't deploy it.

**Comment by Sciss** [comment]
JUnit is correctly registered as a test-scope only dependency in the Maven file: http://search.maven.org/#artifactdetails%7Cde.sciss%7Cws4j%7C0.1.0%7C

**Comment by LucianP91** [comment]
Sorry, my bad. Working fine now.
